### ISSUE TITLE
error, cause unknown

### ISSUE THREAD

**Issue by MearWolf** [jacobwgillespie/plex-sync#8] opened 2016-09-16 09:15 UTC
I'm syncing two users. One syncs fine, the other throws the following error:

```
TypeError: Cannot read property 'Video' of undefined
    at /usr/local/lib/node_modules/plex-sync/lib/plex.js:80:40
    at process._tickCallback (node.js:368:9)
```

**Comment by jacobwgillespie** [comment] 2016-09-17 01:03
Are you trying to sync between two different Plex users in the same pass?  I'm not sure I support that actually, since it uses a single Plex token.  I should add support for that...

**Comment by MearWolf** [comment] 2016-09-17 19:38
In the same pass? Do you mean the home group?

My user is set up in a home group, which appears to be syncing fine. 
The other user is not a member of the plex home group.

**Comment by jacobwgillespie** [comment] 2016-09-17 19:40
Sorry that wasn't clear - I meant are you trying to sync from one user's
watch history to another user's account.

I can try to replicate a non-home user on my end or maybe give you some
instructions for capturing the XML response to see what's going on.

**Comment by MearWolf** [comment] 2016-09-17 22:25
No, both users being synced across two servers. Mine is fine, my other user's gets this error

**Comment by jacobwgillespie** [comment] 2016-09-26 01:48
Can you take a look at the output from the following URL?

```
http://SERVER_HOST/library/sections/SECTION_NUMBER/allLeaves?X-Plex-Token=PLEX_TOKEN
```

If you're able to post it as a comment on this issue that would be awesome (though maybe censor your server's IP address, Plex token, and any other sensitive info).  That should help understand why it isn't working for that particular user.

**Comment by jacobwgillespie** [comment] 2016-10-21 00:05
I'm going to close this issue for now, but feel free to comment if you have any more information and I'll definitely take a look.  👍

**Comment by svjakobs** [comment] 2016-11-01 19:19
Trying to sync two servers, first one running on a synology nas, the other Nvidia shield.
 Trying this link: http://SERVER_HOST/library/sections/SECTION_NUMBER/allLeaves?X-Plex-Token=PLEX_TOKEN

Gives me an "500 Internal Server Error" running the same url with different ipon the nvidia shield gives me a long xml?. so guessing the problem is reading from the synology nas. Any clue on what to do?

**Comment by svjakobs** [comment] 2016-11-01 19:21
Additional comment. it works fine on section 1, its when syncing section two it gives the 500 error.

**Comment by jacobwgillespie** [comment] 2016-11-01 19:26
@svjakobs what type of libraries are sections 1 and 2?  Are they different?  Like is section 1 movies and section 2 TV?

Also to be clear, you're saying this is what you're getting as responses to those links?

* Shield Section 1 - XML
* Synology Section 1 - XML
* Shield Section 2 - XML
* Synology Section 2 - 500 error

**Comment by svjakobs** [comment] 2016-11-01 19:28
Your are correct.

**Comment by svjakobs** [comment] 2016-11-01 19:32
Here is the error I get when running the following command:
plex-sync TOKEN@10.0.0.10/2,r TOKEN@10.0.0.16/2,w

Reading data from 10.0.0.10:32400, 10.0.0.16:32400...
Progress:                      | Elapsed: 0.0s | 100%
TypeError: Cannot read property 'Video' of undefined
    at C:\Users\sven_\AppData\Roaming\npm\node_modules\plex-sync\lib\plex.js:78:40
    at process._tickCallback (node.js:369:9)

**Comment by svjakobs** [comment] 2016-11-01 20:35
Looking at the log from my Synology server, I see an error message for the sql database when trying to do a sync on section 2. I will see if I figure out how to fix this.

**Comment by jacobwgillespie** [comment] 2016-11-02 03:02
> I see an error message for the sql database

Interesting - maybe the issue is with that specific install?  Can you post the exact error from the logs?

**Comment by svjakobs** [comment] 2016-11-02 17:38
Was as corrupt database, I had to remove it and build it again. Now it works
So error on my installation not your tool, so from my side case closed, and I'm looking forward to using plex_sync. Thanks for your help

**Comment by jacobwgillespie** [comment] 2016-11-02 18:11
Sweet, glad you got it sorted! :+1:

**Closed by jacobwgillespie** 2016-11-02 18:11 UTC
